version: '3.4'

services:
  adspot.api:
    image: ${DOCKER_REGISTRY-}adspotapi
    container_name: adspot.api
    build:
      context: .
      dockerfile: AdSpot.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  adspot.database:
    image: postgres:latest
    container_name: adspot.database
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: adspot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  postgresdata:
