version: "3.4"

services:
  adspot.api:
    image: ${DOCKER_REGISTRY-}adspotapi
    container_name: adspot.api
    build:
      context: .
      dockerfile: AdSpot.Api/Dockerfile
    networks:
      - db-network
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      adspot.database:
        condition: service_started

  adspot.database:
    image: postgres:latest
    container_name: adspot.database
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: adspot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - db-network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - adspot.database
    networks:
      - db-network
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    restart: unless-stopped

networks:
  db-network:

volumes:
  postgresdata:
