# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
      - uses: actions/checkout@v2
      - run: |
          dotnet tool restore
          dotnet csharpier --check .
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ./AdSpot.sln
      - name: Build
        run: dotnet build --no-restore ./AdSpot.sln
      - name: Lint
        run: dotnet format --verify-no-changes ./AdSpot.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal ./AdSpot.sln
  create_coverage_report:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ./AdSpot.sln
      - name: Install coverlet
        run: dotnet tool install --global coverlet.console
      - name: Build
        run: dotnet build --no-restore ./AdSpot.sln
      - name: Test
        run: dotnet test --collect "Code Coverage;Format=cobertura" --results-directory "./TestResults/" --settings "AdSpot.Test/CodeCoverage.runsettings" ./AdSpot.sln
      - name: Create coverage report
        run: |
          mkdir -p coverage
          reportgenerator -reports:"TestResults/**/*.xml" -targetdir:coverageReport -reporttypes:Html